
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app-deploy
  labels:
    app: simple-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: govix/simple-nodejs-app:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-svc
  annotations:
    # Optional: This makes it an Internet-facing AWS ELB
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"   # or "classic" for old-style ELB
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: simple-nodejs-app
  ports:
  - port: 80          # external port exposed by the LoadBalancer
    targetPort: 3000  # port inside your container
